#Kaniko to build infrastructure container 

image: 
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

stages:
  - build
  - validate
  - plan 
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json

cache:
  key: "$CI_COMMIT_SHORT_SHA"
  paths:
    - .terraform


build:
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo  "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Docker/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:latest --cache=true

validate:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  stage: validate 
  script:
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - terraform init
    - terraform validate
    - terraform fmt -check=true

merge-review:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  stage: plan
  artifacts:
    name: plan
    paths:
      - $PLAN
    reports:
        terraform: $JSON_PLAN_FILE
  script:
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - terraform plan -out=$PLAN 
    - terraform show --json  $PLAN |  jq  "{resource_changes}" > $JSON_PLAN_FILE
  only:
    - merge_requests
  except:
    - schedules
  dependencies:
    - validate
plan production:
  image: $CI_REGISTRY_IMAGE:latest
  stage: plan
  script:
    - terraform plan -out=$PLAN
    - terraform show --json $PLAN | jq  "{resource_changes}" > $JSON_PLAN_FILE
  artifacts:
    name: plan
    paths:
      - $PLAN
    reports:
        terraform: $JSON_PLAN_FILE
  only:
    - master
  except:
    - schedules
  resource_group: production


apply:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  stage: apply
  dependencies:
    - plan production
  script:
    - terraform apply $PLAN
  only:
    - master
  resource_group: production