#Kaniko to build infrastructure container 

image: 
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

stages:
  - build
  - validate
  - plan 
  - apply


variables:
  TF_IN_AUTOMATION: "true"
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json

cache:
  key: "$CI_COMMIT_SHORT_SHA"
  paths:
    - .terraform


build:
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo  "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Docker/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --cache=true


validate:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  stage: validate 
  script:
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - terraform init modules
    - terraform validate modules
    - terraform fmt -check=true
   


plan:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  stage: plan
  artifacts:
    name: plan
    paths:
      - $PLAN
  script:
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - terraform plan -out=$PLAN modules


apply:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  stage: apply
  dependencies:
    - plan
  script:
    - terraform apply $PLAN
  only:
    - master
